name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.300
        include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project using MSBuild (WPF fix)
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        msbuild ExpenseTrackerApp/ExpenseTrackerApp.csproj /p:Configuration=Release /p:Platform="x86"

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
